### ISSUE TITLE
 PyQt5-Qt5 and loguru error...

### ISSUE THREAD

**Issue by liberte1988** [YarmolenkoD/notpixel#101]
ERROR: Could not find a version that satisfies the requirement PyQt5-Qt5==5.15.15 (from versions: 5.15.2)
ERROR: No matching distribution found for PyQt5-Qt5==5.15.15
WARNING: You are using pip version 21.2.3; however, version 24.2 is available.
You should consider upgrading via the 'C:\temp\notpixel\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Dependencies already installed, skipping installation.
Skipping .env copying
No local changes to save
Already up to date.
No stash entries found.
Starting the bot...
Traceback (most recent call last):
  File "C:\temp\notpixel\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\temp\notpixel\bot\utils\__init__.py", line 1, in <module>
    from .logger import logger, info, warning, debug, success, error, critical
  File "C:\temp\notpixel\bot\utils\logger.py", line 5, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by YarmolenkoD** [comment]
pip install --upgrade pip
pip install -r requirements.txt
