### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by sentient-ai69** [YarmolenkoD/notpixel#102]
File "/home/ubuntu/notpixel/notpixel/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/notpixel/notpixel/main.py", line 8, in main
    await process()
  File "/home/ubuntu/notpixel/notpixel/bot/utils/launcher.py", line 115, in process
    await run_tasks(tg_clients=tg_clients)
  File "/home/ubuntu/notpixel/notpixel/bot/utils/launcher.py", line 140, in run_tasks
    await asyncio.gather(*tasks)
  File "/home/ubuntu/notpixel/notpixel/bot/core/tapper.py", line 1512, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "/home/ubuntu/notpixel/notpixel/bot/core/tapper.py", line 1368, in run
    if re.search("http://", proxy):
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x7bd6be23dae0>

**Comment by sentient-ai69** [comment]
My .env file. I’ve removed the API ID and API Hash but it’s there in the actual file.

API_ID=xxxxxx
API_HASH=xxxxxxxxx

USE_REF=
REF_ID=
PERCENT_OF_REFERRALS_FOR_CREATORS_OF_THE_SOFT=

USE_RANDOM_DELAY_IN_RUN=
RANDOM_DELAY_IN_RUN=

SLEEP_TIME_IN_MINUTES=

ENABLE_AUTO_TASKS=
ENABLE_AUTO_DRAW=
UNSAFE_ENABLE_JOIN_TG_CHANNELS=
ENABLE_CLAIM_REWARD=
ENABLE_AUTO_UPGRADE=

ENABLE_AUTO_JOIN_TO_SQUAD_CHANNEL=
ENABLE_AUTO_JOIN_TO_SQUAD=
SQUAD_SLUG=

DISABLE_IN_NIGHT=
NIGHT_TIME=

ENABLE_CHECK_UPDATED_IMAGE_MODE=
ENABLE_SERVER_MODE=

ENABLE_RANDOM_CUSTOM_TEMPLATE=
RANDOM_TEMPLATE_IDS=

ENABLE_DRAW_CUSTOM_TEMPLATE=
CUSTOM_TEMPLATE_ID=

ENABLE_SSL=

PAINT_REWARD_MAX=
ENERGY_LIMIT_MAX=
RE_CHARGE_SPEED_MAX=

BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=

USE_PROXY_FROM_FILE=False
OPEN_TEMPLATES_LIST_IN_BROWSER=

**Comment by garnatka** [comment]
same here

**Comment by pllusin** [comment]
Same Here

**Comment by MojtabaMirbaqeri** [comment]
I have same issue

**Comment by bacnd** [comment]
I have same issue

**Comment by bacnd** [comment]
I fixed the bug, open the `tapper.py` file in the path `/notpixel/bot/core`. Update like below

![image](https://github.com/user-attachments/assets/84961d5e-2235-457f-afe3-6ce1479a5eb0)

**Comment by pllusin** [comment]
> I fixed the bug, open the `tapper.py` file in the path `/notpixel/bot/core`. Update like below
> 
> ![image](https://private-user-images.githubusercontent.com/5406421/381244856-84961d5e-2235-457f-afe3-6ce1479a5eb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjcyNjQsIm5iZiI6MTczMDI2Njk2NCwicGF0aCI6Ii81NDA2NDIxLzM4MTI0NDg1Ni04NDk2MWQ1ZS0yMjM1LTQ1N2YtYWZlMy02Y2UxNDc5YTVlYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDU0MjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI0M2UwOWM0NjA4NWYxN2IwNDRiNmU2ZTUzNTdkOGI1MTQ5ZWNkYjU0NmNjN2Y0ZjE1NjNhMzUxZDQxMWM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.w2mHHXKzOPrcCCKlRVOS5MITD3egSHKbrRjRQhsccEE)



copy this code :)

`
        if isinstance(proxy, str) and re.search("http://", proxy):
            self.image_scraper_proxies: dict[str, str] = {"http": proxy}
        elif isinstance(proxy, str) and re.search("https://", proxy):
            self.image_scraper_proxies: dict[str, str] = {"http": proxy.replace('https://', 'http://'), "https": proxy}
        elif isinstance (proxy, str) and re.search("socks5://", proxy):
            self.image_scraper_proxies: dict[str, str] = {"http": proxy.replace('socks5://', 'http://'), "socks5": proxy}


`

**Comment by YarmolenkoD** [comment]
@sentient-ai69  @THMaST3R  @pllusin  Already fixed.
