### ISSUE TITLE
Update the README.md file please

### ISSUE THREAD

**Issue by Ashwin3454** [YarmolenkoD/notpixel#104]
What are the default parameters?? (not found in readme.md)

RANDOM_TEMPLATE_IDS=

PAINT_REWARD_MAX=
ENERGY_LIMIT_MAX=
RE_CHARGE_SPEED_MAX=

BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=

OPEN_TEMPLATES_LIST_IN_BROWSER=

**Comment by YarmolenkoD** [comment]
@Ashwin3454

PAINT_REWARD_MAX=7 # max is 7
ENERGY_LIMIT_MAX=7 # max is 7
RE_CHARGE_SPEED_MAX=11 # max is 11

OPEN_TEMPLATES_LIST_IN_BROWSER=True

RANDOM_TEMPLATE_IDS=[6103707977, 1479673219, 1041243367, 2087855212, 2100761925, 508528154, 474917422, 7151956877,5098860372, 751725586, 355876562]

Don't touch this ones:
BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=
