### ISSUE TITLE
TypeError: expected string or bytes-like object, got 'NoneType' Unclosed client session client_session: <aiocfscrape.CloudflareScraper object at 0x000001BA249BD410>

### ISSUE THREAD

**Issue by faerhjio0gase** [YarmolenkoD/notpixel#105]
TypeError: expected string or bytes-like object, got 'NoneType'
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x000001BA249BD410>

**Comment by YarmolenkoD** [comment]
@faerhjio0gase Already fixed. Pull latest changes please
