### ISSUE TITLE
failed to download image

### ISSUE THREAD

**Issue by siestaaaa** [YarmolenkoD/notpixel#107]
when i use custom template, get error failed to download image, what i have to do?

**Comment by YarmolenkoD** [comment]
@siestaaaa Pull latest changes and it should be fixed.

**Comment by YarmolenkoD** [comment]
@siestaaaa And you need real template ID and use it in correct format. 

Examples:

CUSTOM TEMPLATE ID MODE:

ENABLE_DRAW_CUSTOM_TEMPLATE=True
CUSTOM_TEMPLATE_ID=1041243367


RANDOM MODE:

ENABLE_RANDOM_CUSTOM_TEMPLATE=True
RANDOM_TEMPLATE_IDS=[6103707977, 1479673219, 1041243367, 2087855212, 2100761925, 508528154, 474917422, 7151956877, 5098860372, 751725586]
