### ISSUE TITLE
error env

### ISSUE THREAD

**Issue by Namig09** [YarmolenkoD/notpixel#110]
![image](https://github.com/user-attachments/assets/3b35c55c-6be8-407b-857f-b13614661cbe)
I don't understand what's wrong? I changed the .env file, but apparently not as it should be.. can you show me how to do it?

**Comment by YarmolenkoD** [comment]
@Namig09 Edit bot/config/proxies.txt or add the variable to .env file USE_PROXY_FROM_FILE=False
