### ISSUE TITLE
Server Unreachable

### ISSUE THREAD

**Issue by rjrakib69** [YarmolenkoD/notpixel#111]
![image](https://github.com/user-attachments/assets/fba252c1-cc04-4ab2-bb86-e1a31d74d8b0)

**Comment by AntiWarforever** [comment]
same
me too...

**Comment by oreolu-wa** [comment]
Same here

**Comment by rsdt45** [comment]
sameeeeeeeeeeeeee

**Comment by YarmolenkoD** [comment]
@rjrakib69 @rsdt45 @AntiWarforever @oreolu-wa Please off SERVER MODE.

Use the env variable ENABLE_SERVER_MODE=True

Use other modes ENABLE_RANDOM_CUSTOM_TEMPLATE=True or ENABLE_DRAW_CUSTOM_TEMPLATE=True

**Comment by rjrakib69** [comment]
![image](https://github.com/user-attachments/assets/d9797a3b-7922-4dbd-92eb-ab9c64537046)
@YarmolenkoD
@rsdt45 
still same problem
![image](https://github.com/user-attachments/assets/bd7e4f91-b1fc-4b80-9683-5acbd99b0cf2)

**Comment by liberte1988** [comment]
hi said off!
ENABLE_SERVER_MODE=False

**Comment by rsdt45** [comment]
> hi said off! ENABLE_SERVER_MODE=False

thnks really work

**Comment by rjrakib69** [comment]
@liberte1988 
Thanks,it worked
