### ISSUE TITLE
+0pix

### ISSUE THREAD

**Issue by rsdt45** [YarmolenkoD/notpixel#112]
Most of the time I get 0 pix, I waste energy in vain.
![Знімок екрана 2024-11-01 072611](https://github.com/user-attachments/assets/7c1539b2-5b38-4196-919f-de076a1594a6)

**Comment by YarmolenkoD** [comment]
@rsdt45 You can manage it with updating templates ids. For this moment you use default templates. Please update the option in env file RANDOM_TEMPLATE_IDS=[].

Example with not real template ids: RANDOM_TEMPLATE_IDS=[1111111111, 222222222, 333333333]. 

To find template ids use option 3 when run script and it will open browser with list of all actual templates. 

And you need use not popular templates to get more x3 points.
