### ISSUE TITLE
.env long line text

### ISSUE THREAD

**Issue by AntiWarforever** [YarmolenkoD/notpixel#117]
I want create list of ignore task but don't work in a line and give me error 
`BLACK_LIST_TASKS= ['playSpell','playKolo','playAngryMiner','playJetton','telegramShareStory','emojiOnPostTelegramNewsChannel','NotPlatinumReward','connectTonWallet','telegramJoinBoinkersNewsChannel','telegramBoost','telegramJoinAcidGames','AnimalsAndCoins','AnimalsAndCoinsIsland','AnimalsAndCoinsInstall','playCornBattle','NBPSep','inviteAFriend','MergePalsQuests','playAAO','playPiggyPiggy','dailyVIPEnergyPerk','vipGoldPerk','dailyVIPWheelSpins','foxCoinEnergy','DiamoreSep18']`
how can put this in .env?

**Comment by YarmolenkoD** [comment]
@AntiWarforever It relative to another bot https://github.com/YarmolenkoD/boinkers
