### ISSUE TITLE
Как привязывать аккаунт к конкретному прокси?

### ISSUE THREAD

**Issue by mi7f** [YarmolenkoD/notpixel#12]
Можете подсказать как привязать прокси к конкретному аккаунту, чтобы случайно он не использовался на несколько аккаунтах?

**Comment by YarmolenkoD** [comment]
@mi7f на днях сделаю эту фичу, пока нет возможности привязать к конткретному аккаунту

**Comment by masuriii** [comment]
> @mi7f на днях сделаю эту фичу, пока нет возможности привязать к конткретному аккаунту

было бы очень славно

**Comment by Denys7814** [comment]
> @mi7f на днях сделаю эту фичу, пока нет возможности привязать к конткретному аккаунту

<img width="1470" alt="Знімок екрана 2024-10-04 о 17 42 19" src="https://github.com/user-attachments/assets/31030386-d256-422f-aa14-24b529bfe20f">

Приветствую! Подскажите пожалуйста, как исправить эту ошибку?

**Comment by SashaaGrey** [comment]
> @mi7f на днях сделаю эту фичу, пока нет возможности привязать к конткретному аккаунту

ну что получилось сделать? А так же вопрос если евм пустой там только апиид апихеш это нормально?
Ну и я не понял как привязать отдельную проксю к сессии ? сокс5://ип:порт:логин:пароль сессия? Так же?

**Comment by YarmolenkoD** [comment]
@SashaaGrey Пока что оставил это на потом, не было времени закончитт эту логику.
