### ISSUE TITLE
why its happen

### ISSUE THREAD

**Issue by s10ringleader** [YarmolenkoD/notpixel#13]
![image](https://github.com/user-attachments/assets/13ef2999-6b19-450e-a9b4-2436c4e9a643)

**Comment by kholiqsantosa** [comment]
try to remove your sessions file, and create it again

**Comment by YarmolenkoD** [comment]
@kholiqsantosa thanks

**Comment by Toladmin1** [comment]
I have the same issue, and session deleteion and recreation does not help. what may be wrong?

**Comment by YarmolenkoD** [comment]
@Toladmin1 Can you provide your .env please? Looks like you put inncorect ref_id, also can you provide your logs too
