### ISSUE TITLE
Авторизация в телеграм используя прокси

### ISSUE THREAD

**Issue by Zebatuq** [YarmolenkoD/notpixel#14]
Было бы славно иметь возможность создание сессий и авторизации в телеграме через прокси.
Если я не ошибаюсь - в данный момент прокси для этого не используются.

**Comment by YarmolenkoD** [comment]
@Zebatuq спасибо, пересмотрю и если что постараюсь добавить в ближайшее время

**Comment by YarmolenkoD** [comment]
@Zebatuq Записал себе в беклог, как будет время постараюсь имплементировать это, пока как временнное решение, то при создании сесии можешь включать ВПН и менять его. Все равно сесии один раз создаються.

**Comment by HoyT6yK** [comment]
@Zebatuq если используешь линукс попробуй запускать бота через proxychains-ng
