### ISSUE TITLE
Прокачка

### ISSUE THREAD

**Issue by oboroccv** [YarmolenkoD/notpixel#17]
сделайте прокачку по выбору

# =============[upgrades]================
# default is 5 level you can change it your self
PAINT_REWARD_MAX = 5 # max is 7
ENERGY_LIMIT_MAX = 5 # max is 6
RE_CHARGE_SPEED_MAX = 5 # max is 11

**Comment by YarmolenkoD** [comment]
@oboroccv Спасибо, хороший пункт, добавлю это

**Comment by YarmolenkoD** [comment]
@oboroccv Сделал, можешь стягивать последние изменения и тестить.

**Comment by oboroccv** [comment]
> @oboroccv Сделал, можешь стягивать последние изменения и тестить.

спс уже git pull
