### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by dr3ddy-d** [YarmolenkoD/notpixel#19]
Никак не могу запустить бот на linux : 
Пробовал двумя способами pyenv в виртуальном окружении с питоном 3.10
- сбоит трейсами 

а также докером, трейс пишет о том что енв файл пустой

**Comment by YarmolenkoD** [comment]
@dr3ddy-d Скинь свой енв, приватные ключи только замени. И скинь то что тебе выводит python --version

**Comment by YarmolenkoD** [comment]
@dr3ddy-d получилось решить ?

**Comment by dr3ddy-d** [comment]
> @dr3ddy-d получилось решить ?

sorry даже не пробывал, просто на другой бот переехал.
