### ISSUE TITLE
Cant connect to host notpx.app:443

### ISSUE THREAD

**Issue by fnursandi** [YarmolenkoD/notpixel#2]
![image](https://github.com/user-attachments/assets/00f85c0f-ad52-4ffb-8656-4d13657a6903)

Can u please about this?

**Comment by Inquisitor007** [comment]
Unknown error during get user info: Cannot connect to host notpx.app:443 ssl:False [Connection reset by peer]
Продолжают сыпаться ошибки. Обновил бота 5 минут назад.

**Comment by Omnividente** [comment]
Исправил в tapper.py ssl=False, на ssl=True  и ошибка пропала.

**Comment by fnursandi** [comment]
Thanks

**Comment by akashasmaul** [comment]
same, does not work

**Comment by YarmolenkoD** [comment]
Спасибо, скоро запушу обнову

**Comment by YarmolenkoD** [comment]
@akashasmaul @fnursandi Fixed

**Comment by fnursandi** [comment]
> @akashasmaul @fnursandi Fixed

Thanks @YarmolenkoD
