### ISSUE TITLE
Не стартует сессию

### ISSUE THREAD

**Issue by Kilozaur** [YarmolenkoD/notpixel#21]
![image](https://github.com/user-attachments/assets/17dcd52a-0534-4bfc-9715-d3629c5067d6)
![image](https://github.com/user-attachments/assets/f75805b5-390b-4e61-a1b6-cc4e9fe72746)
Что я делаю не так? Бот не стартует сессию

**Comment by YarmolenkoD** [comment]
@Kilozaur Очень странно, попробуй заново и с другим именем, также попробуйю написать не цифри а латиницей имя. И пробовал ли ты создавать сесии в других подобных ботах? Работало ли это у тебя раньше ?

**Comment by Kilozaur** [comment]
Пробовал разные названия. Неа, это единственный бот, я в этом полный ноль, если честно. Просто делал по инструкции.

**Comment by Kilozaur** [comment]
[
    {
        "session_name": "ASDASD",
        "user_agent": "Mozilla/5.0 (Linux; Android 14.0; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.114 Mobile Safari/537.36"
    }
]

Вот что в агенте написано. он сам создался.

**Comment by YarmolenkoD** [comment]
@Kilozaur Попробуй удалить директорию sessions, запустить бота заново, и добавить сесию с нормальным именем без цифр а латиницей. 

Если не поможет, то можешь написать в телеграм группу в саппорт, там быстро отвечают и помогают решить, что бы долго не терять времени, я там тоже могу отвечать.
