### ISSUE TITLE
Cannot connect to host

### ISSUE THREAD

**Issue by kholiqsantosa** [YarmolenkoD/notpixel#22]
![Screenshot_2024-10-02-00-23-59-429_com server auditor ssh client-edit~2](https://github.com/user-attachments/assets/f717106d-7da1-4f77-88bb-6c2723002fdc)

`2024-10-02 00:23:25 | ERROR | worker6 | 😢 worker6 | Unknown error during get user info: Cannot connect to host notpx.app:443 ssl:default [None]`

where's this error coming from?

ENABLE_SSL= False

**Comment by Vigneshwaran30** [comment]
where u able to resolve it ?

**Comment by YarmolenkoD** [comment]
@kholiqsantosa @Vigneshwaran30 First get user info request not always successful. Will add logic to make request again if it not successfull. Thanks for feedback!

**Comment by YarmolenkoD** [comment]
@kholiqsantosa Fixed the issue for now, let me know If you will see it again. Thanks !
