### ISSUE TITLE
Проблема с прокси

### ISSUE THREAD

**Issue by seregafullman** [YarmolenkoD/notpixel#23]
Какие прокси не беру всегда ошибка
Unable to connect due to network issues: Error connecting to HTTP proxy 193.124.189.132:8085: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
Unable to connect due to network issues: Socket error: HTTP proxy server sent invalid response
Unable to connect due to network issues: Socket error: HTTP proxy server sent invalid response
Connection failed! Trying again...
Может есть решение или дело в прокси

**Comment by Denys-Nakonechnyi** [comment]
<img width="1470" alt="Знімок екрана 2024-10-04 о 17 42 19" src="https://github.com/user-attachments/assets/b1161d69-1f74-4fe1-9a8e-17cfca386917">

Добрый день! Подскажите пожалуйста, как решить данную проблему чтоб небыло этой ошибки? Использовал сокс5 и хттп прокси, результат одинаковый(

**Comment by seregafullman** [comment]
> Какие прокси не беру всегда ошибка Unable to connect due to network issues: Error connecting to HTTP proxy 193.124.189.132:8085: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение Unable to connect due to network issues: Socket error: HTTP proxy server sent invalid response Unable to connect due to network issues: Socket error: HTTP proxy server sent invalid response Connection failed! Trying again... Может есть решение или дело в прокси
