### ISSUE TITLE
Если красить по шаблону, отображенному на карте, даёт 3x награду, однако если боту указать это место и нужный цвет, дается обычная награда

### ISSUE THREAD

**Issue by Theslandybrain** [YarmolenkoD/notpixel#24]

**Comment by YarmolenkoD** [comment]
@Theslandybrain Можешь юзать эти переменные для указания правильных цветов и координат:

DRAW_RANDOM_X_DIAPOSON=[480,489]
DRAW_RANDOM_Y_DIAPOSON=[522,525]
DRAW_RANDOM_COLORS=["#ffffff"]

По умолчанию я стараюсь обновлять с правильной позицией. 

Например эти значения значат что будет рисовать ТГ самолет, который находится в середине шаблона.
