### ISSUE TITLE
auto drawing art 

### ISSUE THREAD

**Issue by toastyy00** [YarmolenkoD/notpixel#26]
![image](https://github.com/user-attachments/assets/9961b0ea-2bd4-4785-a845-919f9f08c32d)
If you draw with colors that match the art, your px will be doubled like this.

**Comment by kholiqsantosa** [comment]
Just set your coordinates based on the image on that canvas, if possible, stick to one color.

For example, you want to color only the black parts of the sample image at coordinates x [345, 655] and y [345, 389].

That works for me.

**Comment by YarmolenkoD** [comment]
@toastyy00 You can use the env variable to manage it. 

DRAW_RANDOM_X_DIAPOSON=[480,489]
DRAW_RANDOM_Y_DIAPOSON=[522,525]
DRAW_RANDOM_COLORS=["#ffffff"]

I also update the default values for these fields to get x3 in the right place.

**Comment by toastyy00** [comment]
thank you 😊
