### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by dimscm** [YarmolenkoD/notpixel#27]
![image](https://github.com/user-attachments/assets/0f5fd4e5-bccb-4206-8a8c-e2fc37453929)
can you help me?

**Comment by YarmolenkoD** [comment]
@dimscm Can you provide your .env file please ? And did you update script with latest changes?

**Comment by dimscm** [comment]
![image](https://github.com/user-attachments/assets/42520c26-476f-44ae-9710-fc31531558ca)

**Comment by YarmolenkoD** [comment]
@dimscm Looks good, but either way try to remove "# max is 7, 6, 11" characters.

Also which version of python do you use? You can check it with the terminal command python --version
