### ISSUE TITLE
Night Time Feature

### ISSUE THREAD

**Issue by kholiqsantosa** [YarmolenkoD/notpixel#28]
are you planning to add nighttime hours? It seems necessary to avoid detection.

**Comment by danazor** [comment]
it would be good!

**Comment by YarmolenkoD** [comment]
@kholiqsantosa Ok, thanks, good suggestion, will think about it.

**Comment by YarmolenkoD** [comment]
@kholiqsantosa @danazor Added this env variables to manage it.

    DISABLE_IN_NIGHT=False
    NIGHT_TIME=[23, 6]

**Comment by toastyy00** [comment]
this is still running
DISABLE_IN_NIGHT=True
NIGHT_TIME=[23, 6]

![SmartSelect_20241005_004510_Termius](https://github.com/user-attachments/assets/61c1a1f7-140f-4a66-80fa-87f1dbbea809)
