### ISSUE TITLE
Выдает ошибки при запуске

### ISSUE THREAD

**Issue by beetlejuicerus** [YarmolenkoD/notpixel#29]
<img width="757" alt="Снимок экрана 2024-10-03 в 12 37 48" src="https://github.com/user-attachments/assets/c7e28f27-683d-4dfa-94dd-a08393fe9d31">

Добрый день! Выдает такие ошибки при запуске, в чем может быть проблема?

**Comment by danazor** [comment]
i get same error too @YarmolenkoD 
![59cd954b-fbc6-4663-b0a2-be66f4a5bee5](https://github.com/user-attachments/assets/f75a9364-6a22-4b0b-afd6-4927899d8562)

**Comment by beetlejuicerus** [comment]
Разобрался. Ввел целые числа в env без знака # в эти строки. И все заработало

PAINT_REWARD_MAX=5
ENERGY_LIMIT_MAX=5
RE_CHARGE_SPEED_MAX=5
