### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by akashasmaul** [YarmolenkoD/notpixel#3]
![image](https://github.com/user-attachments/assets/054b5270-8172-4255-a3a6-f6d450d3d4f0)

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**Comment by YarmolenkoD** [comment]
Going to fix it soon

**Comment by YarmolenkoD** [comment]
@akashasmaul Pushed updates, please update script with latest changes and check it, and let me know if it still not working :)

**Comment by YarmolenkoD** [comment]
@akashasmaul If it still not working please use ENABLE_SSL variable in .env file. Try True or False to fix it.

**Comment by akashasmaul** [comment]
![image](https://github.com/user-attachments/assets/ec53bcf5-0c03-411b-8223-a5aadb2e948f)


yeah it works now
