### ISSUE TITLE
Suggest logic

### ISSUE THREAD

**Issue by copycatcodex** [YarmolenkoD/notpixel#30]
is it possible to add logic to justify mismatching colors? so you get 3x more square points

**Comment by YarmolenkoD** [comment]
@copycatcodex Yes, you can use this env variables.

 By default, I'm trying to put the right coordinates and color here. 

DRAW_RANDOM_X_DIAPOSON=[480,489]
DRAW_RANDOM_Y_DIAPOSON=[522,525]
DRAW_RANDOM_COLORS=["#ffffff"]
