### ISSUE TITLE
DISABLE_IN_NIGHT not working properly

### ISSUE THREAD

**Issue by kholiqsantosa** [YarmolenkoD/notpixel#33]
I’ve tried different values here, but it still doesn’t work like it should.

Sometimes when it’s time to sleep, it doesn’t stop. And when it’s time to wake up, it doesn’t start.

**Comment by kholiqsantosa** [comment]
![Screenshot_2024-10-06-02-16-06-890_com server auditor ssh client~2](https://github.com/user-attachments/assets/0bb884e9-d695-4973-ac2f-5a5ea504f1fc)

`DISABLE_IN_NIGHT=False
NIGHT_TIME=[23, 6]`

**Comment by YarmolenkoD** [comment]
@IMPER1A-V @kholiqsantosa

Thanks! Will check it.

 Спасибо! Пересмотрю логику.

**Comment by YarmolenkoD** [comment]
@IMPER1A-V @kholiqsantosa It works now. 

PS. I just forgot to update the logs and say script'll sleep until morning.
