### ISSUE TITLE
Paint in limited space

### ISSUE THREAD

**Issue by kumarKG** [YarmolenkoD/notpixel#34]
How to set coordinates, so bot can auto paint between them. Right now bot is picking random location (x , y axis coordinate) which looks suspicious (of using bots).

**Comment by YarmolenkoD** [comment]
@kumarKG You can use the env variables:

DRAW_RANDOM_X_DIAPOSON=[480,489]
DRAW_RANDOM_Y_DIAPOSON=[522,525]
DRAW_RANDOM_COLORS=["#ffffff"]
