### ISSUE TITLE
Проблема с проксями (socks5)

### ISSUE THREAD

**Issue by l1nuxxx** [YarmolenkoD/notpixel#35]
Не хочет запускаться с socks5 проксями(прокси рабочие, проверял), в чем может быть проблема?

![image](https://github.com/user-attachments/assets/ca1fca90-86aa-42a0-bb95-9efb7b4966fc)

**Comment by l1nuxxx** [comment]
Вот такой прикол нашёл, эти прокси подходят под pyrogram(socks5), но не подходят под aiohttp, а http прокси подходят под aiohttp, но не подходят под pyrogram (Socket error 407) :/

**Comment by YarmolenkoD** [comment]
@l1nuxxx Спасибо, как будет время постараюсь посмотреть.
