### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by kholiqsantosa** [YarmolenkoD/notpixel#36]
yooo, its too many timeout there
can you help me to fix this issue, please...

![Screenshot_2024-10-06-23-17-04-905_com server auditor ssh client](https://github.com/user-attachments/assets/913b7da2-ea4a-4961-8c7a-625024015324)

**Comment by YarmolenkoD** [comment]
@kholiqsantosa Can you specify which coords you are using to draw? I think this is the problem. Because I helped another person to solve the same problem and when he used default env variables, it helped him.

**Comment by YarmolenkoD** [comment]
@kholiqsantosa Fixed.
