### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by glofflive** [YarmolenkoD/notpixel#37]
![image](https://github.com/user-attachments/assets/36f6a644-1e9c-4cef-bf11-69ca94ed558a)

**Comment by YarmolenkoD** [comment]
@glofflive Thanks for feedback, will check it.

Is it work correctly now ?

**Comment by glofflive** [comment]
> @glofflive Thanks for feedback, will check it.
> 
> 
> 
> Is it work correctly now ? 

Yes all is good now. Thanks
