### ISSUE TITLE
тг забанил всю ферму на второй день

### ISSUE THREAD

**Issue by sprtstr** [YarmolenkoD/notpixel#39]
50 номеров на физ симках. пока-пока...

**Comment by faerhjio0gase** [comment]
использовал прокси?

**Comment by HoyT6yK** [comment]
Какие использовал прокси, какой регион симок?

**Comment by sprtstr** [comment]
Симки Укр, прокси Укр, webshare
на других софтах работали четко

**Comment by YarmolenkoD** [comment]
@sprtstr

Паралельно запускал скрипты другие ? Какие скрипты юзаешь еще ? 

ENABLE_JOIN_TG_CHANNELS ? стоит на True? Люди в чатах пишут, что подключение к каналам может быть проблемой.

Летом у меня тоже забанило всю ферму, то как раз сейчас проанализировал, что тогда в скриптах было подключение к чатам.

Сори, что так получилось!

Частично аккаунты разбанить могут, если писать в поддержку, только с разных мейлов нужно. 

Мои частично разбанили, но я не сильно этим занимался, а решил востановить ферму новыми симками.

Если надумаешь покупать новые, то может эта инфа поможет:
- Если ты в Украине покупаешь симки, не знаю по каким ценам, но я беру Vodafone Device, там если на этом сайте брать https://www.itbox.ua/ то можна симку за 80 грн., если регаешь новый акк то дают бонусами 100 грн и можешь на 5 симок применить, доставка бесплатная в некоторые города.
