### ISSUE TITLE
407 Proxy Error

### ISSUE THREAD

**Issue by ryandhikacc** [YarmolenkoD/notpixel#41]
Error:
![image](https://github.com/user-attachments/assets/40269451-2dfa-4a02-9a87-0a978fd0593b)
Proxy is fine:
![image](https://github.com/user-attachments/assets/60b9a908-70a3-42d8-9d3d-ca1cbd47b94e)
Format is correct:
![image](https://github.com/user-attachments/assets/aa1dcd27-d0e4-4eef-8541-8ca9dd1f028d)

**Comment by YarmolenkoD** [comment]
@ryandhikacc  You need to configure your proxy correctly. Are you using webshare proxy? If yes, you need to specify your ip address for authentication in the settings.

**Comment by ryandhikacc** [comment]
Yes im using webshare but the paid one, do i need to use ip authorization? Is username:password not enough? I'll try though

**Comment by ryandhikacc** [comment]
I've tried using ip authorization instead of using username:password and it still throws 407 Authentication Required.

**Comment by YarmolenkoD** [comment]
@ryandhikacc You need use both IP and username:password. And it should work.

**Comment by ryandhikacc** [comment]
> @ryandhikacc You need use both IP and username:password. And it should work.

Works with socks5, with http it doesnt work
