### ISSUE TITLE
Ошибка в рисовании пикселей

### ISSUE THREAD

**Issue by kirajok** [YarmolenkoD/notpixel#42]
Бот ставит пиксель по значению [X, Y-1]. Например если в настройках установлено значение [0,500], то на всех ботах пиксель ставиться в [0, 499]. Смена значений не исправляет ситуацию Установлено последнее обновление.
Отдельная благодарность за бота.

**Comment by YarmolenkoD** [comment]
@kirajok Fixed

**Comment by kirajok** [comment]
good job
