### ISSUE TITLE
I dont know bruh

### ISSUE THREAD

**Issue by ali578745** [YarmolenkoD/notpixel#44]
![image](https://github.com/user-attachments/assets/adfb8e9e-8930-40f2-b32a-5184ae2b4f95)

**Comment by Rollagit** [comment]
you must to edit .env-example name to .env 
then go in file an fill the api_id and hash_ id then save and run again

**Comment by ali578745** [comment]
> you must to edit .env-example name to .env then go in file an fill the api_id and hash_ id then save and run again

![image](https://github.com/user-attachments/assets/99a901d4-e35c-4c7c-91bb-74c651bcb455)

**Comment by YarmolenkoD** [comment]
@ali578745 Which version of python do you use? And give us your .env file, but without app_id and api_hash
