### ISSUE TITLE
Error After selecting create session

### ISSUE THREAD

**Issue by ali578745** [YarmolenkoD/notpixel#45]
![image](https://github.com/user-attachments/assets/1a240bee-3ab5-4672-9208-be12dc54056b)

**Comment by YarmolenkoD** [comment]
@ali578745 Can you provide your .env file without app_id and api_hash, and which python version do you use ?

**Comment by YarmolenkoD** [comment]
@ali578745 You can run this command in terminal to check python version - python --version

**Comment by ali578745** [comment]
> @ali578745 Can you provide your .env file without app_id and api_hash, and which python version do you use ?

its actually a problem with telegram hash number and account ,i changed account and it worked

**Comment by ali578745** [comment]
it was a problem with a specific telegram account
