### ISSUE TITLE
Add Query

### ISSUE THREAD

**Issue by xSamine** [YarmolenkoD/notpixel#46]
can u add query method to run the bot

**Comment by YarmolenkoD** [comment]
@xSamine What kind of query are you referring to? Can you provide more info please

**Comment by aljawary** [comment]
https://github.com/Widiskel/not-pixel-bot

U can check his repo

**Comment by YarmolenkoD** [comment]
@aljawary @xSamine For this moment I'm not support query, but if wil have time I'll implement it later in future.
