### ISSUE TITLE
Use Proxy from file question 

### ISSUE THREAD

**Issue by kholiqsantosa** [YarmolenkoD/notpixel#48]
![Screenshot_2024-10-10-20-12-21-923_com server auditor ssh client~2](https://github.com/user-attachments/assets/cf079c06-5220-4f57-b73f-26fa8ed0618a)
`USE_PROXY_FROM_FILE=False`

![Screenshot_2024-10-10-20-12-33-270_com server auditor ssh client~2](https://github.com/user-attachments/assets/6727c1ac-0606-400d-99da-dbc1a9062381)
`USE_PROXY_FROM_FILE=True`

So basically, I'm wondering if the value False means I'm running this program without any proxy at all? Even though I've got the user_agents.json file ready, which also includes proxy data for each session, when the program runs, the IP for each session doesn't show up.

Can you explain what's going on with that?

**Comment by YarmolenkoD** [comment]
USE_PROXY_FROM_FILE=False
Yes, it means that all sessions are running without a proxy.

**Comment by YarmolenkoD** [comment]
@kholiqsantosa I support proxies only from proxies file in bot/config/proxies directory. 

The script not support proxies from user_agents file for this moment. Maybe will have time to implement it later. 

Thanks for question!
