### ISSUE TITLE
Error: Please edit .env file

### ISSUE THREAD

**Issue by danazor** [YarmolenkoD/notpixel#5]
Hey man, when i run manual or .bat file i got this error.

API_ID=xxx
API_HASH=xxx
USE_REF=False
REF_ID=f1555520xxx
USE_RANDOM_DELAY_IN_RUN=True
RANDOM_DELAY_IN_RUN=[3, 15]
SLEEP_TIME_IN_MINUTES=[120, 180]
ENABLE_AUTO_TASKS=True
ENABLE_AUTO_DRAW=True
ENABLE_JOIN_TG_CHANNELS=True
ENABLE_CLAIM_REWARD=True
ENABLE_AUTO_UPGRADE=False
BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=
USE_PROXY_FROM_FILE=False

idk what should i write on Boosts_black_list and Task_todo_list. and is there a problem with the other values i wrote?

Thanks!

**Comment by hasan1818666891** [comment]
Leave it empty,  only devs can change it.

**Comment by YarmolenkoD** [comment]
@danazor You use not my version of the bot, to use my script with latest updates please follow the two options:

1) install new repo from the link https://github.com/YarmolenkoD/notpixel.git and try run it again from scratch

2) Run the command in terminal
git clone https://github.com/YarmolenkoD/notpixel.git
cd notpixel
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
cp .env-example .env
python3 main.py

**Comment by danazor** [comment]
installed new repo and all good! thanks guys!

**Comment by danazor** [comment]
installed new repo and all good! thanks guys!
