### ISSUE TITLE
Websocket error during painting (x3): 504, message='Gateway Timeout', url=URL('https://notpx.app/api/v1/repaint/start')

### ISSUE THREAD

**Issue by ali578745** [YarmolenkoD/notpixel#52]
![image](https://github.com/user-attachments/assets/c80f9a74-86e1-4fa2-aba6-3c9c9c8abf11)

**Comment by Ajijordison** [comment]
Same here

**Comment by glofflive** [comment]
Same problem

**Comment by berezenko04** [comment]
Same

**Comment by trilecmt** [comment]
Same

**Comment by YarmolenkoD** [comment]
@berezenko04 @trilecmt @glofflive @Ajijordison
Update the variable in .env file to False and it should fix it. Thanks for feedback!

ENABLE_EXPERIMENTAL_X3_MODE=False

**Comment by YarmolenkoD** [comment]
@berezenko04 @trilecmt @glofflive @Ajijordison  For now you can use ENABLE_EXPERIMENTAL_X3_MODE=True variables. I already added handlers for Notpixel server errors.
