### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by ravindu-piumantha** [YarmolenkoD/notpixel#55]
😢 Unknown error during Authorization: Telegram says: [420 FLOOD_WAIT_X] - A wait of 169 seconds is required (caused by "contacts.ResolveUsername")

help me

**Comment by RecursionHs** [comment]
it's tg api limit 
i add some code . it's works fine
```python
            random_delay = random.randint(50, 100)
            logger.info(f"will to get peers first Sleep {random_delay}s")
            await asyncio.sleep(random_delay)
```
![image](https://github.com/user-attachments/assets/ff377db0-5cd1-43b2-acc1-a66e5bdec57d)

**Comment by ravindu-piumantha** [comment]
not working

**Comment by YarmolenkoD** [comment]
@ravindu-piumantha Have you resolved the issue? Did you try to use other scripts before ?
