### ISSUE TITLE
No points

### ISSUE THREAD

**Issue by Niyaz-Mahmud** [YarmolenkoD/notpixel#59]
A little update ⚡️

Say goodbye to bots and random repaints. 

Now painting outside of templates does not give rewards. Zero 🧨

🌈🌈🌈🌈🌈🌈🌈🌈

November is coming. Time for high-profile events.

**Comment by YarmolenkoD** [comment]
@Niyaz-Mahmud Use the env variables and it will paint with template ENABLE_EXPERIMENTAL_X3_MODE=True
