### ISSUE TITLE
Unknown error during get user info: 401

### ISSUE THREAD

**Issue by danazor** [YarmolenkoD/notpixel#6]
When I first run the script it works fine but after going to sleep mode it gives the error in the screenshot and enters the same loop. After x minutes of sleep it goes back to sleep mode.

Sorry for the quality of the screenshot.

I am writing the error I get:

Unknown error during get user info: 401, message='Unauthorized' , url=URL('https://notpx.app/api/v1/users/me')

By the way I don't encounter any problems when I enter the application from the phone.
![9d4f4aa0-be32-493d-a596-e4890524c751](https://github.com/user-attachments/assets/45536e83-8c08-4b2f-9a3f-a2fd9c960a85)

**Comment by YarmolenkoD** [comment]
@danazor Thanks, will check it

**Comment by YarmolenkoD** [comment]
@danazor Try recreating the session. It helped one person to resolve the error.
