### ISSUE TITLE
0 points

### ISSUE THREAD

**Issue by KIRUNI77** [YarmolenkoD/notpixel#64]
![123](https://github.com/user-attachments/assets/a131d24e-f5b4-48d5-862e-7110cde2aebf)
There are often 0 points

**Comment by Niyaz-Mahmud** [comment]
Use different template.

**Comment by ksardsas2015** [comment]
same with all of templates

**Comment by PythonGitHub1** [comment]
how i can change a templates?

**Comment by KIRUNI77** [comment]
> Use different template.

I have a random template mod enabled. and still 0 points

**Comment by PythonGitHub1** [comment]
> > Use different template.
> 
> I have a random template mod activated, but I still have 0 points.

I I made settings like the script coder and 0 for painting became less frequent.

**Comment by ali578745** [comment]
> how i can change a templates?(where find id other templates?)

there is a template list json file in the folder

**Comment by YarmolenkoD** [comment]
@PythonGitHub1 Also if you want to use your own template you can use your telegramID it equal to your template in notpixel.

**Comment by YarmolenkoD** [comment]
@KIRUNI77 I work on it. Will try to make updates on this week to improve results. Thanks for feedback!
