### ISSUE TITLE
Fix the issue getting 0 pixel 

### ISSUE THREAD

**Issue by savan878** [YarmolenkoD/notpixel#67]
![Uploading Screenshot_2024-10-15-15-59-09-995_com.termux.png…]()

**Comment by YarmolenkoD** [comment]
@savan878 Please use not popular template, for example you can use default template Id and it should better. Also I still working to make it more effectively. Thanks for feedback!

I use 355876562 the template and for now it works not bad.

**Comment by YarmolenkoD** [comment]
@savan878 Try now. It should works better and more stable.
