### ISSUE TITLE
No Drawing

### ISSUE THREAD

**Issue by Safin007** [YarmolenkoD/notpixel#68]
After new update it just claiming mining, not drawing,
after mining reward successfully claimed the going to sleep for 45-50 minutes

**Comment by Dolzhansky** [comment]
+

**Comment by Dolzhansky** [comment]
Same shit

**Comment by Danny972** [comment]
Same

**Comment by YarmolenkoD** [comment]
@Safin007 @Dolzhansky @Danny972 Notpixel pushed some updates which broken my logic. I pushed minor fixes to improve chance to get of x3 points. Please pull latest updates. 

Also going to fix it in few days.
