### ISSUE TITLE
no drawing

### ISSUE THREAD

**Issue by Safin007** [YarmolenkoD/notpixel#70]
[
![IMG_20241015_184035](https://github.com/user-attachments/assets/2e247eee-4ec3-47bf-8d0a-d8367add7413)
](url)

**Comment by YarmolenkoD** [comment]
@Safin007 You can try now. It works better and more stable.

**Comment by YarmolenkoD** [comment]
@Safin007 let me know if it works fine or no. thanks for feedback!
