### ISSUE TITLE
CUSTOM_TEMPLATE_ID

### ISSUE THREAD

**Issue by shairkhan2** [YarmolenkoD/notpixel#71]
from where i can get CUSTOM_TEMPLATE_ID

**Comment by Safin007** [comment]
should you use custom template on .env file or use is by default?

**Comment by GinkySan** [comment]
choosing a template will have little effect on the effectiveness of the script, but for greater confidence, you can use the desktop version NOT Pixel to find a template that has few subscribers and which often overlaps with other colors. This way you will be sure that the pixel supplied by the script request will not be painted over and will give you all the points
