### ISSUE TITLE
рисовалка

### ISSUE THREAD

**Issue by MuscleeMuseum** [YarmolenkoD/notpixel#8]
Даниил, подскажи, есть ли возможность, как вариант, внести например свои цвета и пиксели чтобы он по ним шел, ну или хотя бы чтоб ты добавил какой-то рисунок, и мы все его рисовали. А то я так понимаю, сейчас там рисуется флаг, но разрабы пишут, что за такое можно отлететь в бан, и скорее нас всех могут побрить

**Comment by YarmolenkoD** [comment]
@MuscleeMuseum Привет, спасибо за фидбек, хороший момент, нужно подумать, добавлю параметры для этого и скоро запушу

**Comment by YarmolenkoD** [comment]
@MuscleeMuseum Вот такие параметры скоро запушу

| **DRAW_RANDOM_X_DIAPOSON**  |       Range of pixels on the x-axis, randomly on which it will draw (default - [0,100])        |
| **DRAW_RANDOM_Y_DIAPOSON**  |       Range of pixels on the н-axis, randomly on which it will draw (default - [0,100])        |
|   **DRAW_RANDOM_COLORS**    | List of colors that will be randomly selected for painting  (default - ["#000000"]) |

**Comment by YarmolenkoD** [comment]
@MuscleeMuseum Потом может получится что то лучше сделать, возможно какой то масив цветов и пикселей куда рисовать, и от туда буде выбирать уже

**Comment by YarmolenkoD** [comment]
@MuscleeMuseum Запушил

**Comment by MuscleeMuseum** [comment]
@YarmolenkoD Крутяк, спасибо, полетел тестить!
