### ISSUE TITLE
0 poınts problem

### ISSUE THREAD

**Issue by scoterbey** [YarmolenkoD/notpixel#81]
how can you fix this problm

**Comment by protonmeacc** [comment]
ишак поставь картинку менее популярную себе , а не стандартную. или иди в шашки играй 


> how can you fix this problm

**Comment by YarmolenkoD** [comment]
@scoterbey Thanks for feedback! Working on it, will fix it soon

**Comment by YarmolenkoD** [comment]
@scoterbey Please pull latest changes and use ENABLE_SERVER_MODE=True value in .env file to get more points :)
