### ISSUE TITLE
Error when program tries to paint pixel

### ISSUE THREAD

**Issue by lodity** [YarmolenkoD/notpixel#86]
unsupported operand type(s) for -: 'int' and 'str'
![image](https://github.com/user-attachments/assets/f5c1fd52-0794-4e7e-9b4c-0b2c550eeb79)

**Comment by YarmolenkoD** [comment]
@lodity Thanks for feedback! will try to figure out it

**Comment by YarmolenkoD** [comment]
@lodity  Can you share your .env file please?

**Comment by lodity** [comment]
USE_REF=True
REF_ID=f1067557054
PERCENT_OF_REFERRALS_FOR_CREATORS_OF_THE_SOFT=0

USE_RANDOM_DELAY_IN_RUN=
RANDOM_DELAY_IN_RUN=

SLEEP_TIME_IN_MINUTES=

ENABLE_AUTO_TASKS=
ENABLE_AUTO_DRAW=
UNSAFE_ENABLE_JOIN_TG_CHANNELS=
ENABLE_CLAIM_REWARD=
ENABLE_AUTO_UPGRADE=

ENABLE_AUTO_JOIN_TO_SQUAD_CHANNEL=
ENABLE_AUTO_JOIN_TO_SQUAD=
SQUAD_SLUG=

DISABLE_IN_NIGHT=True
NIGHT_TIME=[2, 11]

ENABLE_RANDOM_CUSTOM_TEMPLATE=
RANDOM_TEMPLATE_IDS=

ENABLE_DRAW_CUSTOM_TEMPLATE=
CUSTOM_TEMPLATE_ID=

ENABLE_SSL=True

PAINT_REWARD_MAX=
ENERGY_LIMIT_MAX=
RE_CHARGE_SPEED_MAX=

BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=

USE_PROXY_FROM_FILE=True

**Comment by YarmolenkoD** [comment]
@lodity Please pull latest changes and try run again and let me know if you still have the issue
