### ISSUE TITLE
The problem when the bot draws

### ISSUE THREAD

**Issue by wentyy4** [YarmolenkoD/notpixel#87]
![1](https://github.com/user-attachments/assets/20dcfde3-62f9-46e3-9c49-037e5baec585)
when the bot tries to draw, it has this problem: Unknown error: unsupported operand type(s) for -: 'int' and 'str'

**Comment by YarmolenkoD** [comment]
@wentyy4 Thanks for feedback ! Will try to figure out it

**Comment by YarmolenkoD** [comment]
@wentyy4 Can you share your .env file please?

**Comment by wentyy4** [comment]
API_ID=
API_HASH=

USE_REF=
REF_ID=
PERCENT_OF_REFERRALS_FOR_CREATORS_OF_THE_SOFT=

USE_RANDOM_DELAY_IN_RUN=
RANDOM_DELAY_IN_RUN=

SLEEP_TIME_IN_MINUTES=

ENABLE_AUTO_TASKS=
ENABLE_AUTO_DRAW=
UNSAFE_ENABLE_JOIN_TG_CHANNELS=
ENABLE_CLAIM_REWARD=
ENABLE_AUTO_UPGRADE=

ENABLE_AUTO_JOIN_TO_SQUAD_CHANNEL=
ENABLE_AUTO_JOIN_TO_SQUAD=
SQUAD_SLUG=

DISABLE_IN_NIGHT=
NIGHT_TIME=

ENABLE_RANDOM_CUSTOM_TEMPLATE=
RANDOM_TEMPLATE_IDS=

ENABLE_DRAW_CUSTOM_TEMPLATE=
CUSTOM_TEMPLATE_ID=

ENABLE_SSL=

PAINT_REWARD_MAX=
ENERGY_LIMIT_MAX=
RE_CHARGE_SPEED_MAX=

BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=

USE_PROXY_FROM_FILE=True

**Comment by wentyy4** [comment]
@YarmolenkoD

**Comment by sentient-ai69** [comment]
Same error

**Comment by YarmolenkoD** [comment]
@wentyy4 @sentient-ai69 Trying to reproduce it and figure out it. Do you still have the issue?

**Comment by YarmolenkoD** [comment]
@wentyy4 @sentient-ai69 And try to pull latest changes I think it should be fixed now

**Comment by wentyy4** [comment]
@YarmolenkoD 
![1](https://github.com/user-attachments/assets/8a827356-59de-4e44-a3f6-d6f7585eea4c)
now new error

**Comment by wentyy4** [comment]
@YarmolenkoD 
![1](https://github.com/user-attachments/assets/c50a5691-c54f-49c7-b698-cce7d92f973e)
now new error

**Comment by YarmolenkoD** [comment]
@wentyy4 It is ok, I added new mode to getting more x3 points. If it not works for you now, you can of it with this variable in env file ENABLE_SERVER_MODE=False.

**Comment by wentyy4** [comment]
@YarmolenkoD anyway, this error

**Comment by YarmolenkoD** [comment]
@wentyy4 Already fixed it, let me know it you still gettin this error

**Comment by sentient-ai69** [comment]
It still doesn’t work. But I found the solution. First you need to create a session. Then go to telegram account and click “Yes, it’s me” to verify. Then start the script and draw.
