### ISSUE TITLE
Not Painting the custom template

### ISSUE THREAD

**Issue by asish1346** [YarmolenkoD/notpixel#89]
![Screenshot 2024-10-22 114550](https://github.com/user-attachments/assets/31a5602a-7401-4ed5-82dd-f32abd678e59)

here is the env....

![Screenshot 2024-10-22 114632](https://github.com/user-attachments/assets/f7280c22-214b-4646-a712-c9accb9b438d)

it"s Subscribing to another template...

**Comment by antofaka** [comment]
some problem

**Comment by asish1346** [comment]
Okay Let Me Check @YarmolenkoD

**Comment by YarmolenkoD** [comment]
@asish1346 Is it works now ?
