### ISSUE TITLE
Server unreachable

### ISSUE THREAD

**Issue by lodity** [YarmolenkoD/notpixel#91]
![image](https://github.com/user-attachments/assets/b3a6932d-c47e-480b-bff9-00764a0a3f52)

**Comment by YarmolenkoD** [comment]
@lodity It is normal, server can be unreachable sometimes, but it will rerun in few attempts or in next cycle.

**Comment by lodity** [comment]
I checked the accessibility to notpxapi.xyz using my proxy and the ping works.
![image](https://github.com/user-attachments/assets/73944da8-b7bb-46f1-a09d-7a8d48a8fda9)

**Comment by YarmolenkoD** [comment]
@lodity This is normal, sometimes the server may be unavailable. But you can disable server mode with the variable ENABLE_SERVER_MODE=False, and use your own template, but use non popular templates with no more than 500 users on the template, and it will give you a better chance to get x3 points. 

And please pul latest changes too. Thanks for feddback :)
