### ISSUE TITLE
CUSTOM_TEMPLATE_ID

### ISSUE THREAD

**Issue by protonmeacc** [YarmolenkoD/notpixel#92]
Now CUSTOM_TEMPLATE_ID doesn't work at all. Receives +0. I took an unpopular picture. The field is completely painted over. 
Server mode - False

![image](https://github.com/user-attachments/assets/89fbacf7-14b9-43e3-b2fd-eeb1ccf94e65)

**Comment by YarmolenkoD** [comment]
@protonmeacc For this moment the best solution it to use ENABLE_SERVER_MODE=True (it will give you more x3 points), I will improve other modes later. Thanks for feedback!

**Comment by YarmolenkoD** [comment]
@protonmeacc Custom template mode should be fixed now, but use non popular templates with no more than 500 users on the template, and it will give you a better chance to get x3 points
