### ISSUE TITLE
Problem with the server

### ISSUE THREAD

**Issue by wentyy4** [YarmolenkoD/notpixel#93]
![1](https://github.com/user-attachments/assets/4bd56b29-73e5-4da2-a4cb-21b882554541)
I waited until it tried to connect 20/20 times, then this is what it showed, it tried to draw, but adds 0

**Comment by YarmolenkoD** [comment]
@wentyy4 This is normal, sometimes the server may be unavailable. But you can disable server mode with the variable ENABLE_SERVER_MODE=False, and use your own template, but use non popular templates with no more than 500 users on the template, and it will give you a better chance to get x3 points
